### ISSUE TITLE
Bot not responding in groups

### ISSUE THREAD

**Issue by Noammac** [suyashb95/wordbot#2]
I added the bot to my group that has two friends and PollBot, they didn't seem to interfere for the first hour but after an hour I get a message from my friend saying it doesn't work, I hopped onto the group to check what happened:

> Me: /help@LexicoBot
> _Wordbot is typing..._
> _3 Members_
> Me: /define digress
> _Wordbot is typing..._
> _3 Members_
> Me: /define@LexicoBot digress
> _Wordbot is typing..._
> _3 Members_

The bug didn't seem to affect regular Lexicobot though outside of the group though.

**Comment by suyashb95** [comment]
Fixed it now, please check.
