### ISSUE TITLE
Bot not working at all

### ISSUE THREAD

**Issue by Noammac** [suyashb95/wordbot#3]
The bot does not respond to any command, not in private chat and not in groups. Did not respond on two tested devices.
![Imgur http://i.imgur.com/3iXyRo7.gifv](http://i.imgur.com/3iXyRo7.gifv)

**Comment by Noammac** [comment]
Fixed by itself?

**Comment by suyashb95** [comment]
Haha no idea. I'll check the logs.

**Comment by suyashb95** [comment]
The bot was acting up because it was trying to message a group it was kicked out of. Telegram kept throwing it a 403. I'll fix it today.
