### ISSUE TITLE
[Query] How to use the /use function in Google Sheets?

### ISSUE THREAD

**Issue by ucalyptus** [suyashb95/wordbot#5]
Hi there @Suyash458 ,
thanks for the bot, it's super helpful!
Are you aware of the question above?

Corresponding to the word given in column 1, I want the sentence output of /use {column1} in column 2 .

Can you suggest a way to do this in Google Sheets?

**Comment by suyashb95** [comment]
Hey @ucalyptus, thank you! I haven't come across such a use case but, there are a few options here

1) ~~You can use services like integromat or IFTTT to iterate over rows in your spreadsheet and send a Telegram message for every row. The response can be appended back to the spreadsheet
https://www.integromat.com/en/integration/2128-get-telegram-messages-for-new-google-sheets-rows
https://www.integromat.com/en/integration/2127-save-telegram-messages-to-a-google-sheets-spreadsheet~~
This requires the bot's API token

2) You could get a Wordnik API key from [here](https://developer.wordnik.com/) and make use of their [Python 3 API bindings](https://github.com/wordnik/wordnik-python3) or repurpose the source code of this project for your use

3) You can use [WiktioanaryParser](https://github.com/Suyash458/WiktionaryParser) to source examples for words in your spreadsheet. The output won't be the same as the bot though, and it might not work for all the words in the sheet
